- hosts: 'all'
  remote_user: <user-name>
  vars:
    ansible_ssh_private_key_file: <ssh-key-path>
    ansible_shell_allow_world_readable_temp: true
    
    
  tasks:
    - name: Print out debug message
      vars:
        msg: |
          Applying playbook to:
            {{ ansible_fqdn }}  
            {{ ansible_default_ipv4.address }}  
      debug:
        msg: "{{ msg.split('\n') }}"




    # Add node.js
    - name: Add the NodeSource package signing key
      become: yes
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: Add nodejs 16 LTS repo location for apt
      become: yes
      apt_repository:
        repo: deb https://deb.nodesource.com/node_16.x bullseye main
        update_cache: yes
    - name: Install the Nodejs from NodeSource repo
      become: yes
      apt:
        update_cache: yes
        name: nodejs
        state: present